ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common \
    && add-apt-repository -y ppa://kgilmer/regolith-stable \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      regolith-desktop \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* \
    && rm -rf /var/lib/apt/lists/*

RUN echo "i3-gnome-flashback" > /etc/skel/.xsession

