[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # color scheme
repo = 'lifepillar/vim-solarized8'

[[plugins]] # color scheme
repo = 'mhartington/oceanic-next'

[[plugins]] # color scheme
repo = 'jacoborus/tender.vim'

[[plugins]] # color scheme
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

#[[plugins]]
#repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'vim-scripts/diffchar.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#[[plugins]]
#repo = 'leafgarland/typescript-vim'
#repo = 'HerringtonDarkholme/yats.vim'

#[[plugins]]
#repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'rhysd/clever-f.vim'

