[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # color scheme
repo = 'jacoborus/tender.vim'
hook_add = '''
  " If you have vim >=8.0 or Neovim >= 0.1.5
  if (has("termguicolors"))
   set termguicolors
  endif
  
  " For Neovim 0.1.3 and 0.1.4
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  
  " Theme
  syntax enable

  " set airline theme
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'tender'

  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
  au MyAutoCmd VimEnter * nested colorscheme tender

  " tmux上でのTrue Color対応
  " see http://qiita.com/yami_beta/items/ef535d3458addd2e8fbb
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

